
// This file was auto-generated by ML.NET Model Builder. 

using SentimentModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
SentimentModel.ModelInput sampleData = new SentimentModel.ModelInput()
{
    DayOfWeek = @"thu",
    Category = @"Books",
    ItemCost = 62F,
    Online = 1F,
};

// Make a single prediction on the sample data and print results
var predictionResult = SentimentModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Satisfaction with predicted Satisfaction from sample data...\n\n");


Console.WriteLine($"DayOfWeek: {@"thu"}");
Console.WriteLine($"Category: {@"Books"}");
Console.WriteLine($"ItemCost: {62F}");
Console.WriteLine($"Satisfaction: {3F}");
Console.WriteLine($"Online: {1F}");


Console.WriteLine($"\n\nPredicted Satisfaction: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

